services:
  backend:
    build: ./backend
    container_name: auctionos_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/auctionos
      - SECRET_KEY=changethiskeyinproduction
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    container_name: auctionos_celery
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/auctionos
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=changethiskeyinproduction
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: auctionos_db
    environment:
      - POSTGRES_DB=auctionos
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data

  postgis:
    image: postgis/postgis:15-3.4
    container_name: auctionos_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auctionos_gis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: auctionos_redis
    ports:
      - "6379:6379"

volumes:
  postgres_main_data:
  postgres_data:
